# Generated by Django 4.1.2 on 2022-11-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ua", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userattr", name="openObjectsInNewWindow",),
    ]
