# Generated by Django 4.1.2 on 2022-10-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acl",
                    models.CharField(
                        default='{"read": ["*"], "o_mod": ["*"], "a_mod": ["&"], "report": ["*"] }',
                        max_length=1000,
                        verbose_name="Права доступа",
                    ),
                ),
                ("isGrp", models.BooleanField(default=False, verbose_name="Группа")),
                ("order", models.IntegerField(default=-1, verbose_name="Порядок")),
                (
                    "name",
                    models.CharField(
                        default="Новый контрагент",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dbcore.agent",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Агент",
                "verbose_name_plural": "Агенты",
                "ordering": ["-isGrp", "parent_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="CostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acl",
                    models.CharField(
                        default='{"read": ["*"], "o_mod": ["*"], "a_mod": ["&"], "report": ["*"] }',
                        max_length=1000,
                        verbose_name="Права доступа",
                    ),
                ),
                ("isGrp", models.BooleanField(default=False, verbose_name="Группа")),
                ("order", models.IntegerField(default=-1, verbose_name="Порядок")),
                (
                    "name",
                    models.CharField(
                        default="Новая статья", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "isOutcome",
                    models.BooleanField(default=True, verbose_name="Расходная"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#AAAAAAFF", max_length=20, verbose_name="Цвет"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dbcore.costtype",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-isGrp", "parent_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="FinOper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acl",
                    models.CharField(
                        default='{"read": ["*"], "o_mod": ["*"], "a_mod": ["&"], "report": ["*"] }',
                        max_length=1000,
                        verbose_name="Права доступа",
                    ),
                ),
                (
                    "moment",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=16, verbose_name="Сумма"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2000,
                        null=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "importTag",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Метка импорта",
                    ),
                ),
                (
                    "agentFrom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agentFrom",
                        to="dbcore.agent",
                        verbose_name="Агент Откуда",
                    ),
                ),
                (
                    "agentTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agentTo",
                        to="dbcore.agent",
                        verbose_name="Агент Куда",
                    ),
                ),
                (
                    "costType",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costType",
                        to="dbcore.costtype",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
                "ordering": ["-moment"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acl",
                    models.CharField(
                        default='{"read": ["*"], "o_mod": ["*"], "a_mod": ["&"], "report": ["*"] }',
                        max_length=1000,
                        verbose_name="Права доступа",
                    ),
                ),
                ("isGrp", models.BooleanField(default=False, verbose_name="Группа")),
                ("order", models.IntegerField(default=-1, verbose_name="Порядок")),
                (
                    "name",
                    models.CharField(
                        default="Новый проект", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "prefFinOperLogIntv",
                    models.IntegerField(
                        default=-1, verbose_name="Интервал журнала операций"
                    ),
                ),
                (
                    "prefFinOperLogIntv_n",
                    models.IntegerField(
                        default=1, verbose_name="Параметр интервала журнала операций"
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=20000,
                        null=True,
                        verbose_name="Заметки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dbcore.project",
                        verbose_name="Родитель",
                    ),
                ),
                (
                    "prefAgentGroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefAgentGroup",
                        to="dbcore.agent",
                        verbose_name="Группа контрагентов",
                    ),
                ),
                (
                    "prefCostTypeGroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefCostTypeGroup",
                        to="dbcore.costtype",
                        verbose_name="Группа статей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["-isGrp", "parent_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        quality=90,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="finoper_photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "finOper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbcore.finoper",
                        verbose_name="Операция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
                "ordering": ["finOper"],
            },
        ),
        migrations.AddField(
            model_name="finoper",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dbcore.project",
                verbose_name="Проект",
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=-1, verbose_name="Порядок")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=16, verbose_name="Сумма"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        default="",
                        max_length=2000,
                        null=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "costType",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dbcore.costtype",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbcore.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бюджет",
                "verbose_name_plural": "Бюджеты",
                "ordering": ["costType", "order"],
            },
        ),
    ]
