# Generated by Django 4.1.2 on 2022-10-30 23:32

import dbcore.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("dbcore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="acl",
            field=models.CharField(
                default='{"read": ["*"], "crt": ["&"], "mod": ["&"], "report": ["*"] }',
                max_length=1000,
                verbose_name="Права доступа",
            ),
        ),
        migrations.AlterField(
            model_name="costtype",
            name="acl",
            field=models.CharField(
                default='{"read": ["*"], "crt": ["&"], "mod": ["&"], "report": ["*"] }',
                max_length=1000,
                verbose_name="Права доступа",
            ),
        ),
        migrations.AlterField(
            model_name="costtype",
            name="color",
            field=models.CharField(
                default="#AAAAAA", max_length=20, verbose_name="Цвет"
            ),
        ),
        migrations.AlterField(
            model_name="finoper",
            name="acl",
            field=models.CharField(
                default='{"read": ["*"], "crt": ["&"], "mod": ["&"], "report": ["*"] }',
                max_length=1000,
                verbose_name="Права доступа",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to=dbcore.models.getPhotoLocation,
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="acl",
            field=models.CharField(
                default='{"read": ["*"], "crt": ["&"], "mod": ["&"], "report": ["*"] }',
                max_length=1000,
                verbose_name="Права доступа",
            ),
        ),
    ]
