# Generated by Django 4.1.2 on 2022-11-17 17:10

import dbcore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcore", "0003_sysparam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                upload_to=dbcore.models.getPhotoLocation, verbose_name="Фото"
            ),
        ),
    ]
